apiVersion: v1
kind: Service
metadata:
  name: llm-transformers
  namespace: llm-inference
  labels:
    app: llm-transformers
spec:
  type: ClusterIP
  ports:
  - port: 8012
    targetPort: 8012
    protocol: TCP
    name: http
  selector:
    app: llm-transformers
---
apiVersion: v1
kind: Service
metadata:
  name: llm-vllm
  namespace: llm-inference
  labels:
    app: llm-vllm
spec:
  type: ClusterIP
  ports:
  - port: 8013
    targetPort: 8013
    protocol: TCP
    name: http
  selector:
    app: llm-vllm
---
apiVersion: v1
kind: Service
metadata:
  name: llm-tensorrt
  namespace: llm-inference
  labels:
    app: llm-tensorrt
spec:
  type: ClusterIP
  ports:
  - port: 8014
    targetPort: 8014
    protocol: TCP
    name: http
  selector:
    app: llm-tensorrt
